---
rabbitmq_password: "CHANGE_ME_rabbitmq"
minio_root_user: "CHANGE_ME_minio_user"
minio_root_password: "CHANGE_ME_minio_password"
grafana_admin_password: "CHANGE_ME_grafana"
vault_role_id: "CHANGE_ME_vault_role_id"
redis_connection_string: "127.0.0.1:6379,password=B@dhi$1234,abortConnect=false"
