---
rabbitmq_password: "B@dhi$1234"
minio_root_user: "dhanmanqaadmin"
minio_root_password: "B@dhi!1234"
grafana_admin_password: "B@dhi$123" # need to check this this to a more secure password
vault_role_id: "a99097a2-28fe-e62d-c3f3-d50aec6abc6d"
vault_secret_id: "0deac4d1-c454-7976-452a-d32feb62f3de"
redis_connection_string: "127.0.0.1:6379,password=B@dhi$1234,abortConnect=false"
