---
# REPLACE THESE before running — store real values in Vault / ansible-vault
rabbitmq_password: "B@dhi$1234"
minio_root_user: "dhanmanprodadmin"
minio_root_password: "B@dh!$1234"
grafana_admin_password: "Dhanman@Grafana2024"
vault_role_id: "CHANGE_ME_vault_role_id"
vault_secret_id: "CHANGE_ME_vault_secret_id"
redis_password: "rdB@yce-Codd(x->y)"
postgres_exporter_password: "PgMon@Dhanman2024"
